### ISSUE TITLE
reading from a specific worksheet

### ISSUE THREAD

**Issue by mvitcostal** [aydinthedev/mapexcel#2]
Hi,
is it possible to read from a specific worksheet?

Thanks

**Comment by aydinthedev** [comment]
Hi,

You can map different DTOs to the same or different sheets by sheet number or name. The WorksheetBuilder class handles that.

```
ExcelTypeRegistry.Register<Foo>(foo =>
{
    foo.Worksheet(x=> ..)
});
```
